CREATE TABLE student
(
    id               int GENERATED BY DEFAULT AS IDENTITY,
    name             varchar(255),
    surname          varchar(255),
    dob              date,
    primary_skill    varchar(255),
    created_datetime timestamp,
    updated_datetime timestamp
);

CREATE TABLE phone
(
    id         int GENERATED BY DEFAULT AS IDENTITY,
    student_id int,
    number     varchar(50)
);

CREATE TABLE subject
(
    id    int GENERATED BY DEFAULT AS IDENTITY,
    name  varchar(255),
    tutor varchar(255)
);

CREATE TABLE exam_result
(
    id         int GENERATED BY DEFAULT AS IDENTITY,
    student_id int,
    subject_id int,
    mark       smallint
);
